# Generated by Django 4.1.7 on 2023-03-06 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0007_maritalstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.city')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.country')),
                ('departament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.departament')),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.district')),
                ('zone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('second_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('second_lastname', models.CharField(max_length=15)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('consanguinity', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=30, unique=True)),
                ('picture', models.ImageField(null=True, upload_to='foto')),
                ('first_name', models.CharField(max_length=15)),
                ('second_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('second_lastname', models.CharField(max_length=15)),
                ('date_birth', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('birth_certificate', models.BooleanField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disability_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.disability')),
                ('gender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.gender')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
                ('nationality_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.country')),
                ('native_language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.language')),
                ('religion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.religion')),
                ('tutor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('second_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('second_lastname', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('number_children', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marital_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.maritalstatus')),
            ],
        ),
    ]
