# Generated by Django 4.1.7 on 2023-02-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(choices=[('F', 'Femenino'), ('M', 'Maculino')], max_length=1)),
            ],
        ),
    ]
