# Generated by Django 4.1.7 on 2023-03-01 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='niveleducativo',
            old_name='name',
            new_name='nombre',
        ),
    ]
