# Generated by Django 4.1.7 on 2023-02-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_degree_educationalinstitution_educationallevel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NivelEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('descripcion', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TipoIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Turn',
            new_name='Asignatura',
        ),
        migrations.RenameModel(
            old_name='Educationallevel',
            new_name='Barrio',
        ),
        migrations.RenameModel(
            old_name='Modality',
            new_name='CentroEducativo',
        ),
        migrations.RenameModel(
            old_name='Municipality',
            new_name='Ciudad',
        ),
        migrations.RenameModel(
            old_name='Educationalinstitution',
            new_name='DelegacionDepartamental',
        ),
        migrations.RenameModel(
            old_name='Typeincome',
            new_name='Departamento',
        ),
        migrations.RenameModel(
            old_name='Section',
            new_name='Discapacidad',
        ),
        migrations.RenameModel(
            old_name='Subject',
            new_name='Etnia',
        ),
        migrations.RenameModel(
            old_name='Degree',
            new_name='Grado',
        ),
        migrations.DeleteModel(
            name='Sex',
        ),
        migrations.RenameField(
            model_name='asignatura',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='barrio',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='centroeducativo',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='ciudad',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='delegaciondepartamental',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='discapacidad',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='etnia',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='grado',
            old_name='name',
            new_name='nombre',
        ),
    ]
